-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 21:48:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema iara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iara` DEFAULT CHARACTER SET utf8 ;
USE `iara` ;

-- -----------------------------------------------------
-- Table `iara`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`Course` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `id_user_author` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `duration` VARCHAR(45) NULL DEFAULT NULL,
  `difficulty` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `icon` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`Class` (
  `id_class` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `difficulty` VARCHAR(45) NULL DEFAULT NULL,
  `index` INT NULL DEFAULT NULL,
  `Course_id_course` INT NOT NULL,
  PRIMARY KEY (`id_class`, `Course_id_course`),
  INDEX `fk_Class_Course1_idx` (`Course_id_course` ASC) VISIBLE,
  CONSTRAINT `fk_Class_Course1`
    FOREIGN KEY (`Course_id_course`)
    REFERENCES `iara`.`Course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`Question` (
  `id_question` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `Class_id_class` INT NOT NULL,
  `Class_Course_id_course` INT NOT NULL,
  `index` INT NULL,
  PRIMARY KEY (`id_question`, `Class_id_class`, `Class_Course_id_course`),
  INDEX `fk_Question_Class1_idx` (`Class_id_class` ASC, `Class_Course_id_course` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Class1`
    FOREIGN KEY (`Class_id_class` , `Class_Course_id_course`)
    REFERENCES `iara`.`Class` (`id_class` , `Course_id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`Alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`Alternative` (
  `id_alternative` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL DEFAULT NULL,
  `correct` TINYINT NULL DEFAULT NULL,
  `Question_id_question` INT NOT NULL,
  PRIMARY KEY (`id_alternative`, `Question_id_question`),
  INDEX `fk_Alternative_Question1_idx` (`Question_id_question` ASC) VISIBLE,
  CONSTRAINT `fk_Alternative_Question1`
    FOREIGN KEY (`Question_id_question`)
    REFERENCES `iara`.`Question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `logo` VARCHAR(45) NULL DEFAULT NULL,
  `bio` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`User_has_Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`User_has_Course` (
  `id_user_has_course` INT NOT NULL AUTO_INCREMENT,
  `User_id_user` INT NOT NULL,
  `Course_id_course` INT NOT NULL,
  PRIMARY KEY (`id_user_has_course`),
  INDEX `fk_User_has_Course_Course1_idx` (`Course_id_course` ASC) VISIBLE,
  INDEX `fk_User_has_Course_User1_idx` (`User_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Course_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `iara`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Course_Course1`
    FOREIGN KEY (`Course_id_course`)
    REFERENCES `iara`.`Course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`User_has_Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`User_has_Class` (
  `User_id_user` INT NOT NULL,
  `Class_id_class` INT NOT NULL,
  `Class_Course_id_course` INT NOT NULL,
  `completed` TINYINT NULL DEFAULT NULL,
  `progress` INT NULL,
  PRIMARY KEY (`User_id_user`, `Class_id_class`, `Class_Course_id_course`),
  INDEX `fk_User_has_Class_Class1_idx` (`Class_id_class` ASC, `Class_Course_id_course` ASC) VISIBLE,
  INDEX `fk_User_has_Class_User1_idx` (`User_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Class_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `iara`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Class_Class1`
    FOREIGN KEY (`Class_id_class` , `Class_Course_id_course`)
    REFERENCES `iara`.`Class` (`id_class` , `Course_id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`Achievement` (
  `id_achievement` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_achievement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`User_has_achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`User_has_achievement` (
  `User_id_user` INT NOT NULL,
  `achievement_id_achievement` INT NOT NULL,
  PRIMARY KEY (`User_id_user`, `achievement_id_achievement`),
  INDEX `fk_User_has_achievement_achievement1_idx` (`achievement_id_achievement` ASC) VISIBLE,
  INDEX `fk_User_has_achievement_User1_idx` (`User_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_achievement_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `iara`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_achievement_achievement1`
    FOREIGN KEY (`achievement_id_achievement`)
    REFERENCES `iara`.`achievement` (`id_achievement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iara`.`Paragraph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iara`.`Paragraph` (
  `id_paragraph` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1023) NULL,
  `image` VARCHAR(63) NULL,
  `Class_id_class` INT NOT NULL,
  `Class_Course_id_course` INT NOT NULL,
  `index` INT NULL,
  PRIMARY KEY (`id_paragraph`, `Class_id_class`, `Class_Course_id_course`),
  INDEX `fk_Paragraph_Class1_idx` (`Class_id_class` ASC, `Class_Course_id_course` ASC) VISIBLE,
  CONSTRAINT `fk_Paragraph_Class1`
    FOREIGN KEY (`Class_id_class` , `Class_Course_id_course`)
    REFERENCES `iara`.`Class` (`id_class` , `Course_id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `iara`.`User_validation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS iara.User_validation (
  id_user_validation INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NULL DEFAULT NULL,
  password VARCHAR(45) NULL DEFAULT NULL,
  User_id_user INT NOT NULL,
  PRIMARY KEY (id_user_validation, User_id_user),
  CONSTRAINT fk_User1
    FOREIGN KEY (User_id_user)
    REFERENCES iara.User (id_user)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
